icons_format = "{icon}"

[theme]
theme = "nord-dark"

[icons]
icons = "material-nf"
# [icons.overrides]
# bat = ["|E|", "|_|", "|=|", "|F|"]
# bat_charging = "|^| "

[[block]]
block = "kdeconnect"
bat_critical = 10
bat_warning = 20

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:25,rot_interval:0.5) $play $volume|}"
format_alt = " $player "
[[block.click]]
button = "left"
action = "play_pause"
[[block.click]]
button = "middle"
widget = "."
action = "toggle_format"
[[block.click]]
button = "up"
action = "volume_up"
[[block.click]]
button = "down"
action = "volume_down"

[[block]]
block = "sound"
device_kind = "sink"
format = " $icon {$volume.eng(w:2) |}"
show_volume_when_muted = true
headphones_indicator = true
[[block.click]]
button = "left"
cmd = "pulsemixer"

[[block]]
block = "sound"
format = "$icon {$volume.eng(w:2) |}"
device_kind = "source"
show_volume_when_muted = true
[[block.click]]
button = "left"
cmd = "pulsemixer"

[[block]]
block = "cpu"
info_cpu = 20
warning_cpu = 50
critical_cpu = 90

[[block]]
block = "memory"
format = "$icon $mem_used_percents.eng(w:2) "
format_alt = "$icon_swap $swap_used_percents.eng(w:2) "
[[block.click]]
button = "right"
cmd = "htop"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " $icon ssd: $available.eng(w:2)"

[[block]]
block = "disk_space"
path = "/mnt/new_storage/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " storage: $available.eng(w:2)"

[[block]]
block = "disk_space"
path = "/mnt/raid/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
format = " raid: $available.eng(w:2) "

[[block]]
block = "time"
interval = 1
format = " $timestamp.datetime(f:'%a %d-%m-%Y %H:%M:%S') "
